### ISSUE TITLE
Contact Deletion: 401 Operation not allowed

### ISSUE THREAD

**Issue by RobinJayaswal** [mailjet/mailjet-apiv3-nodejs#129]
This repo has the following example in `send.js`:

```
const Mailjet = require('./mailjet-client')

const client = new Mailjet(
  process.env.MJ_APIKEY_PUBLIC,
  process.env.MJ_APIKEY_PRIVATE
)

client.delete('contact').id('23539759').request()
  .then(e => console.log(e.body))
  .catch(e => console.log(e))
```

However, when I try this with my master API key, I get `Error: Unsuccessful: 401 Operation not allowed`.

Is this an error? Is there another way for me to programmatically delete contacts?

**Comment by scroll17** [comment]
Hey @RobinJayaswal 

You receive this error because you not owner of this contact and that mean that you can't delete not your contact. 
If you replace `contactId (23539759)` passed in code example with your `contractId` you will get the expected result.

You should ignore this file.
MailJet client exports from the file `mailjet-client.js` and this file not require `send.js`.

**Comment by scroll17** [comment]
This issue will be closed
