### ISSUE TITLE
Int32 overflow : Template language error

### ISSUE THREAD

**Issue by ziadsarour** [mailjet/mailjet-apiv3-nodejs#132]
Hi,

When i tried to send an email via the send API I was facing to a "template language error" (my email was in a "blocked" status).

I then figured out that this error happened when I passed a timestamp to the "Variables" parameter (example : 1607607812738)

I guessed it might be a int32 overflow issue and made some tests to be sure.
- myDate : 2147483646 - OK
- myDate : 2147483647 - OK
- myDate : 2147483648 - BLOCKED

**Comment by kroleek** [comment]
I also run into this issue :/
Thanks for pointing me out in right direction!

Is there error log or any way how to find what is wrong? 
Because anything I get from the message detail is _blocked status_, also in stats page there was no explanation for that.

**Comment by scroll17** [comment]
Hey @ziadsarour @kroleek 

I reproduced your error with the same data and i too receive error "template language error" and status "blocked".
But i was find two solutions for this problem.

At the page [Templates error management](https://dev.mailjet.com/email/template-language/sendapi/#templates-error-management) provided information about template errors and how you can manage these errors.

In code example below i send email with variable which have int32 overflow and i passed `TemplateErrorReporting` property which defined email Address where a message with the error description is sent to: 
```javascript
const mailjet = new Mailjet(
  process.env.MJ_APIKEY_PUBLIC,
  process.env.MJ_APIKEY_PRIVATE
)

const request = mailjet
    .post('send', { version: 'v3.1' })
    .request({
        Messages: [
            {
                From: {
                    Email: 'myemail@gmail.com',
                    Name: 'Username',
                },
                To: [
                    {
                        Email: 'myemail@gmail.com',
                        Name: 'Username',
                    },
                ],
                Variables: {
                    day: 'today',
                    myDateOne: 2147483648,
                },
                TextPart: `Test Email Day: {{var:day:"monday"}} Date: {{var:myDateOne}}`,
                HTMLPart: `<h3>Test Email</h3> <br/> Day: {{var:day:"monday"}} <br/> Date: {{var:myDateOne}}`,
                Subject: 'Email with int32 overflow',
                TemplateLanguage: true,
                TemplateErrorReporting: {
                    Email: 'myemail@gmail.com',
                    Name: 'Username',
                }
            },
        ],
    })
    
request
    .then((result) => {
        console.dir(result.body, { depth: 10 })
    })
    .catch((err) => {
        console.log(err)
    })
```
And i received a message from `templating-language-error@mailjet.com` with subject `Error while evaluating Mailjet Templating language for message "Email with int32 overflow"` and in the mail body contained this message `A template language occurred: stoi`.
How i understand `stoi` [it's C++ function](https://www.cplusplus.com/reference/string/stoi/) which convert string to integer and in C++ be default type integer have 32-bit size. 

If you want that this limitation was be resolved you need go to [Mailjet Support Center](https://app.mailjet.com/support) and create ticket, go to chat room or something like that.

Below i provided two solutions how you can solved this problem right now: 

1. In the first case you can use string instead of integer
I'm tested this and it's working without error and data as string are displayed without quotes: 

```javascript
const request = mailjet
    .post('send', { version: 'v3.1' })
    .request({
        Messages: [
            {
                From: {
                    Email: 'myemail@gmail.com',
                    Name: 'Username',
                },
                To: [
                    {
                        Email: 'myemail@gmail.com',
                        Name: 'Username',
                    },
                ],
                Variables: {
                    day: 'today',
                    myDateOne: '2147483648',
                },
                TextPart: `Test Email Day: {{var:day:"monday"}} Date: {{var:myDateOne}}`,
                HTMLPart: `<h3>Test Email</h3> <br/> Day: {{var:day:"monday"}} <br/> Date: {{var:myDateOne}}`,
                Subject: 'Email with int32 overflow',
                TemplateLanguage: true,
                TemplateErrorReporting: {
                    Email: 'myemail@gmail.com',
                    Name: 'Username',
                }
            },
        ],
    })
```

2. In the second case you can use [Template language functions](https://dev.mailjet.com/email/template-language/reference/#functions) with data type double.
I'm tested this and i'm receive expected result.
It's working without error and data as double after using template function `Int(number)` are converted to integer using this case you can have more integer capacity: 

In code example i used value `21474836489992.01` which is much more than `2147483648`: 
```javascript
const request = mailjet
    .post('send', { version: 'v3.1' })
    .request({
        Messages: [
            {
                From: {
                    Email: 'myemail@gmail.com',
                    Name: 'Username',
                },
                To: [
                    {
                        Email: 'myemail@gmail.com',
                        Name: 'Username',
                    },
                ],
                Variables: {
                    day: 'today',
                    myDateOne: 21474836489992.01,
                },
                TextPart: `Test Email Day: {{var:day:"monday"}} Date: {{Int(var:myDateOne)}}`,
                HTMLPart: `<h3>Test Email</h3> <br/> Day: {{var:day:"monday"}} <br/> Date: {{Int(var:myDateOne)}}`,
                Subject: 'Email with double',
                TemplateLanguage: true,
                TemplateErrorReporting: {
                    Email: 'myemail@gmail.com',
                    Name: 'Username',
                }
            },
        ],
    })
```

**But you need keep in mind that floating part of the number is required** and if you passed not `21474836489992.01` but `21474836489992.00` you will be receive the same error that if you passed integer - "template language error" and status "blocked".

**Comment by scroll17** [comment]
This issue will be closed
