### ISSUE TITLE
Some attachments failed to be delivered

### ISSUE THREAD

**Issue by mkbctrl** [mailjet/mailjet-apiv3-nodejs#140]
Hello 👋 

I have a small issue with messages that include `.zip` attachments. No matter the file size (tested 1.7mb and 25mb) the API does not deliver the message. 

In case where the size does not exceed the 15 mb file limit you have specified in docs, I would expect message to be delivered or to get an error (meanwhile api returnes "success" status).

In 25mb case I would expect to get an error unless the limit is just a soft limit, is it?

In any other case I tried so far, both the message and the attachments are delivered as promised (unless it's .zip). 
I don't see any .zip or file type related info in your docs unless I missed it.

Thanks in advance for any assistance here.

P.S. Spam is empty, tested on gmail.
P.S.2 I am not sure that's the best place to post that issue, so sorry for any inconvenience.

**Comment by scroll17** [comment]
Hey @mkbctrl 

I reproduce your error and i have the same behavior in the gmail.
But if you send the files with binary type  (`.zip` one of them) you need keep in mind that different mail clients are have different behavior with this file type. 

I tested your case in two different email clients: `Gmail` and `Outlook` and below i writing how i reproduced your error and how i fixed her: 

In the first case i was using wrong code for load `.zip` file and i send the invalid `Base64Content` data: 
```javascript
const Mailjet = require('./mailjet-client')
const path = require('path')
const fs = require('fs')
const util = require('util')

const mailjet = new Mailjet(
  process.env.MJ_APIKEY_PUBLIC,
  process.env.MJ_APIKEY_PRIVATE
)

;(async () => {
    try {
        const zipContentType = 'application/zip'

        const fileName = 'attachment.zip'   // file size: 500b
        const filePath = path.resolve(__dirname, fileName)
        const fileData = await util.promisify(fs.readFile.bind(fs))(filePath, { encoding: 'utf8' }) 

        const request = await mailjet
            .post('send', { version: 'v3.1' })
            .request({
                Messages: [
                    {
                        From: {
                            Email: 'pilot@gmail.com',
                            Name: 'Pilot',
                        },
                        To: [
                            {
                                Email: 'passenger@gmail.com', // 'passenger@outlook.com'
                                Name: 'Passenger',
                            }
                        ],
                        TextPart: `Test Email with .zip file`,
                        HTMLPart: `<h3>Test Email</h3> <br/> <h2>With .zip file</h2>`,
                        Subject: 'Email with .zip file',
                        Attachments: [
                            {
                                ContentType: zipContentType,
                                Filename: fileName,
                                Base64Content: Buffer.from(fileData).toString('base64')
                            }
                        ]
                    },
                ],
            })

        console.log(request)
        console.dir(request.body, { depth: 10 })
    } catch (err) {
        delete err.response;
        console.log(err)
    }
})();
```

And after perform this code i receive this response: 
```
[Object: null prototype] {
  Messages: [
    [Object: null prototype] {
      Status: 'success',
      CustomID: '',
      To: [
        [Object: null prototype] {
          Email: 'passenger@gmail.com',
          MessageUUID: '3d8457e9-2426-4d02-98a6-90892df351ed',
          MessageID: '1152921516575913910',
          MessageHref: 'https://api.mailjet.com/v3/REST/message/1152921516575913910'
        }
      ],
      Cc: [],
      Bcc: []
    }
  ]
}
```

When i'm send this email with attachment to the Gmail i receive success response but on the [Dashboard page](https://app.mailjet.com/) i see that my email not delivered and it have status _"Soft-bounce"_.

But if i'm send also email to the Outlook i receive success response and on the [Dashboard page](https://app.mailjet.com/) i see that my email delivered and it have status _"Delivered"_ and i received this email with `.zip` attachment on my Outlook client where i can download this `.zip` file.

But when i try to open downloaded `.zip` file i received the error "An error occurred while loading the archive" from my OS. 
This is so because how i said in above this code is wrong and he send invalid `.zip` file.

**Now we can conclude that Gmail checks the validity and integrity of the `.zip` file before accepting this email, but Outlook does not do such a check and simply sends the recipient everything that he received**

And what about code example. 
He is wrong because i try to convert `binary` encoding before to `utf8` and then to `base64` but `utf8` can't correctly represent the `binary` encoding: 
```javascript
...
        const fileName = 'attachment.zip'
        const filePath = path.resolve(__dirname, fileName)
        const fileData = await util.promisify(fs.readFile.bind(fs))(filePath, { encoding: 'utf8' })  
...
       {
         Attachments: [
                            {
                                ContentType: zipContentType,
                                Filename: fileName,
                                Base64Content: Buffer.from(fileData).toString('base64')
                            }
           ]
       }
...       
``` 

In the second case i was using valid code for load `.zip` file which have size `5.5MB` and i was receive this email with attachment in the both Gmail and Outlook:
```javascript
const Mailjet = require('./mailjet-client')
const path = require('path')
const fs = require('fs')
const util = require('util')

const mailjet = new Mailjet(
  process.env.MJ_APIKEY_PUBLIC,
  process.env.MJ_APIKEY_PRIVATE
)

;(async () => {
    try {
        const zipContentType = 'application/zip'

        const fileName = 'big-attachment.zip'   // file size: 5.5MB
        const filePath = path.resolve(__dirname, fileName)
        const fileData = await util.promisify(fs.readFile.bind(fs))(filePath, { encoding: 'base64' })

        const request = await mailjet
            .post('send', { version: 'v3.1' })
            .request({
                Messages: [
                    {
                        From: {
                            Email: 'pilot@gmail.com',
                            Name: 'Pilot',
                        },
                        To: [
                            {
                                Email: 'passenger@gmail.com',
                                Name: 'Passenger',
                            }
                        ],
                        TextPart: `Test Email with .zip file`,
                        HTMLPart: `<h3>Test Email</h3> <br/> <h2>With .zip file</h2>`,
                        Subject: 'Email with .zip file',
                        Attachments: [
                            {
                                ContentType: zipContentType,
                                Filename: fileName,
                                Base64Content: fileData
                            }
                        ]
                    },
                ],
            })

        console.log(request)
        console.dir(request.body, { depth: 10 })
    } catch (err) {
        delete err.response;
        console.log(err)
    }
})();
```
In this case i was right away load the `.zip` from `binary` to `base64` encoding: 
```javascript
...
        const fileName = 'attachment.zip'
        const filePath = path.resolve(__dirname, fileName)
        const fileData = await util.promisify(fs.readFile.bind(fs))(filePath, { encoding: 'base64' })
...
```

And after perform this code i receive this response: 
```
[Object: null prototype] {
  Messages: [
    [Object: null prototype] {
      Status: 'success',
      CustomID: '',
      To: [
        [Object: null prototype] {
          Email: 'passenger@gmail.com',
          MessageUUID: '3d8457e9-2426-4d02-98a6-90811df351ed',
          MessageID: '1152921516575923910',
          MessageHref: 'https://api.mailjet.com/v3/REST/message/1152921516575923910'
        }
      ],
      Cc: [],
      Bcc: []
    }
  ]
}
```

And when i using this code example i was successfully receive email with `.zip` attachment in the both Gmail and Outlook clients and in from each client i downloaded this attachment and hes was opened without any erros and all data in attachment was integrity.

**Summary:** you must be sure that you are sending the binary type file correctly and that the data is an validity and integrity.

**Comment by scroll17** [comment]
This issue will be closed
