### ISSUE TITLE
API Key not working from process.env file

### ISSUE THREAD

**Issue by 19sajib** [mailjet/mailjet-apiv3-nodejs#142]
**here is the code I have been using>**
```
const mailjet = require ('node-mailjet')
.connect(process.env.MJ_APIKEY_PUBLIC, process.env.MJ_APIKEY_PRIVATE)

const request = mailjet.post("send").request({
    "Messages":[
      {
        "From": {
          "Email": "contact2sajib@gmail.com",
          "Name": "Abu"
        },
        "To": [
          {
            "Email": email,
            "Name": firstName
          }
        ],
        "Subject": "Sajib - Activate your account",
        "TextPart": "Activate Your Account",
        "HTMLPart": `<h3 align="center" style="color:red;">We just need to validate your email address to activate your account.<br /> 
                     Simply click <a href="${process.env.CLIENT_URL}/accountactivation/${token}">here</a> </h3>
                     <br /> <h3 align="center">Or copy the link down below and paste it on your browser.</h3>
                     <br /> <h3>${process.env.CLIENT_URL}/accountactivation/${token}</h3>
                     <br /> <button style="color:blue; align:center" ><a href="${process.env.CLIENT_URL}/accountactivation/${token}">Activate Your Account</a></button>
                     <br />May the delivery force be with you!`,
        "CustomID": "AppGettingStartedTest"
      }
    ]
  })
  request
    .then((result) => {
      console.log(result.body)
    })
    .catch((err) => {
      console.log(err.statusCode)
      console.log(err)
    })
```
**here is the error>**
```
status: 401,
      text: '{"ErrorIdentifier":"bd3e238f-0f99-4189-8b6e-75eba4b7bb60","StatusCode":401,"ErrorMessage":"API key authentication/authorization failure. You may be unauthorized to access the API or your API key may be expired. Visit API keys management section to check your keys."}',    
      method: 'POST',
      path: '/v3.1/send'
    },
    created: false,
    accepted: false,
    noContent: false,
    badRequest: false,
    unauthorized: true,
    notAcceptable: false,
    forbidden: false,
    notFound: false,
    unprocessableEntity: false,
    type: 'application/json',
    charset: 'UTF-8',
    links: {},
    setEncoding: [Function: bound ],
    redirects: [],
    [Symbol(kCapture)]: false
  }
}
```
**If I use API keys directly instead of (process.env.MJ_APIKEY_PUBLIC, process.env.MJ_APIKEY_PRIVATE) then it works fine like>**

```
const mailjet = require ('node-mailjet')
.connect(8738473872, 29729841244)
Rest of the code same...
```

**My question is what is the problem with the process.env file, while the process.env file working perfectly fine with other Keys. **
**Does anybody know why is this problem occurring and the solutions??**

**Comment by flo-sch** [comment]
Hello, I am not from Mailjet, but I managed to have this working fine using the [dotenv](https://www.npmjs.com/package/dotenv) package.
(Loading environment parameters is not provided natively by this package, this is something you need to do yourself)

**Comment by 2sajib2** [comment]
> Hello, I am not from Mailjet, but I managed to have this working fine using the [dotenv](https://www.npmjs.com/package/dotenv) package.
> (Loading environment parameters is not provided natively by this package, this is something you need to do yourself)

**will you tell me how did you do that?**

**Comment by flo-sch** [comment]
How you implement it depends how you build your application.

If you use a bundler such as webpack, there are ways to integrate environment parameters thanks to some plugins:
- https://webpack.js.org/plugins/environment-plugin/
- https://github.com/mrsteele/dotenv-webpack

Otherwise, as mentioned, you can directly use the dotenv package, just follow the [usage instructions](https://www.npmjs.com/package/dotenv#usage)

PS: you probably want to load environment parameters globally in your application, not just for the maillet part

**Comment by scroll17** [comment]
Hey @19sajib 
You receive the error "API key authentication/authorization failure. You may be unauthorized ..." because you have invalid values in variables `process.env.MJ_APIKEY_PUBLIC` and `process.env.MJ_APIKEY_PRIVATE`

I tested this case with correct values and i can't reproduce this error.

How said @flo-sch you can use npm package [dotenv](https://www.npmjs.com/package/dotenv#usage) or set value to this variables in the begin of source code file: 
```javascript
// requires...

process.env.MJ_APIKEY_PUBLIC = '9d4aded9.....'
process.env.MJ_APIKEY_PRIVATE = 'd73162b4.....'

// the main code below
```

As well you can use environment variables
For Linux / Mac: `MJ_APIKEY_PUBLIC='9d4aded9...' MJ_APIKEY_PRIVATE='d73162b4...' node <filename>.js`
For Windows: 
- CMD: `set MJ_APIKEY_PUBLIC=9d4aded9 node <filename>.js`
- Powershell: `$env:MJ_APIKEY_PUBLIC="9d4aded9" node <filename>.js` 

Another cross-platform use case it's npm package [cross-env](https://www.npmjs.com/package/cross-env): 
`cross-env MJ_APIKEY_PUBLIC=9d4aded9 MJ_APIKEY_PRIVATE=d73162b4 node <filename>.js`

**Comment by scroll17** [comment]
This issue will be closed
