### ISSUE TITLE
Better Errors

### ISSUE THREAD

**Issue by OlivierCuyp** [mailjet/mailjet-apiv3-nodejs#17]
Hi guys,

Instead of extending the basic Error object with your own properties like here:

https://github.com/mailjet/mailjet-apiv3-nodejs/blob/master/mailjet-client.js#L189

It might be a better idea to follow a structure that already exists like : 

https://www.npmjs.com/package/http-errors

Error logging would be easier for consumers.

**Comment by arnaudbreton** [comment]
Hi @OlivierCuyp, thanks a lot for the feedback, highly appreciated! We'll plan to improve this.
We would love to review and include your contribution. Feel free to open a PR.
Thanks.

**Comment by lukastl21** [comment]
Hello,

I second this.
Also, timeout errors are currently not caught.
The body is just an empty object:
https://github.com/mailjet/mailjet-apiv3-nodejs/blob/master/mailjet-client.js#L184

and then it will never get assigned anything, because the result does not have a status:
https://github.com/mailjet/mailjet-apiv3-nodejs/blob/master/mailjet-client.js#L187

So you don't get an error, but a success with an empty object

**Comment by derhuerst** [comment]
Also, consider [`boom`](https://github.com/hapijs/boom#readme).

**Comment by Zhivko-Mailjet** [comment]
@derhuerst Thanks for the suggestion, we may consider it in future, if needed.
