### ISSUE TITLE
Decimal in for loop: error in template language

### ISSUE THREAD

**Issue by jdG-** [mailjet/mailjet-apiv3-nodejs#180]
Hi,
When I send an array like the next one to `client.post('send', { version: 'v3.1' })`.
NOT WORKING (https://app.mailjet.com/reports/emails/1naolNV06Bj):
```javascript
things: [
  {
    name: 'test 1',
    completion: '100',
    success: '15',
  },
  {
    name: 'Test 2',
    completion: '43',
    success: '15.79',
  },
],
```
I'm facing to an "error in template language".
After several tries, I found that if I change the floating number in the success field of the last element of the array by an integer it works. 
But if I put the floating number in the first element of the array it works.
WORKING (https://app.mailjet.com/reports/emails/GAcaZvyjn2):
```javascript
things: [
  {
    name: 'test 1',
    completion: '43',
    success: '15.79',
  },
  {
    name: 'Test 2',
    completion: '100',
    success: '15',
  },
],
```
Template Id: 3270229
node-mailjet: 3.3.4

**Comment by scroll17** [comment]
Hey @jdG- 
I was tried to reproduce your error with the same data (collection `things`) and i'm not getting error.

I was used template from collection of templates in MailJet as property `TemplateID` in the message and i'm haven't error.
Also i was used template as property `HTMLPart` in the message and i didn't get the error either.

Both templates from collection in MailJet and as property `HTMLPart` have the same structure.

Below i provide code example which i used:
```javascript
const mailjet = new Mailjet(
  process.env.MJ_APIKEY_PUBLIC,
  process.env.MJ_APIKEY_PRIVATE
)

const request = mailjet
    .post('send', { version: 'v3.1' })
    .request({
        Messages: [
            {
                From: {
                    Email: 'pilot@mailjet.com',
                    Name: 'Pilot',
                },
                To: [
                    {
                        Email: 'passenger_1@mailjet.com',
                        Name: 'Passenger 1',
                    },
                ],
                Variables: {
                    things: [
                        {
                            name: 'test 1',
                            completion: 100,
                            success: 15,
                        },
                        {
                            name: 'Test 2',
                            completion: 43,
                            success: 15.79,
                        },
                    ],
                    day: 'today'
                },
                "TextPart": `Test Email Day: {{var:day:"monday"}} Things:`,
                "HTMLPart": `<h3>Test Email</h3> <br/> Day: {{var:day:"monday"}} <br/> Things: {% for thing in var:things %}<ul><li>name: {{ thing.name }}</li><li>completion: {{ thing.completion }}</li><li>success: {{ thing.success }}</li></ul>{% endfor %}`,
                TemplateLanguage: true,
                Subject: 'Email with loop',
            },
        ],
    })

request
    .then((result) => {
        console.dir(result.body, { depth: 10 })
    })
    .catch((err) => {
        console.log(err)
    })
```

And it my response: 
```
[Object: null prototype] {
  Messages: [
    [Object: null prototype] {
      Status: 'success',
      CustomID: '',
      To: [
        [Object: null prototype] {
          Email: 'passenger_1@mailjet.com',
          MessageUUID: '0a57d210-b0e8-46f1-b8b8-6f9e68887b25',
          MessageID: '288230388079214342',
          MessageHref: 'https://api.mailjet.com/v3/REST/message/288230388079214442'
        }
      ],
      Cc: [],
      Bcc: []
    }
  ]
}
```

Are you sure that you uses template correctly?
You can read [DEV GUIDE - How use a template](https://dev.mailjet.com/email/guides/send-api-V3/#use-a-template) and [Templating language reference](https://dev.mailjet.com/email/template-language/reference/)

I as SDK developer haven't access to reports and you templates.
So that if you can provide more information such as request code example and template code example i can help you.

**Comment by scroll17** [comment]
This issue will be closed
