### ISSUE TITLE
Property "Contact", alternate key value "simone@wicka.com.au" could not be resolved to an ID

### ISSUE THREAD

**Issue by wicka-aus** [mailjet/mailjet-apiv3-nodejs#185]
Hi

I am getting this error on ListRecipient endpoint

Validate request object: { name: 'Simone', email: 'simone@wicka.com.au' }

Once worked but now causing issues.

Docs state I only need to provide this information:

To add a contact to a list, you need to create a new list recipient with a POST request on the [/listrecipient](https://dev.mailjet.com/email/reference/contacts/subscriptions#v3_post_listrecipient) resource. You can specify the contact by either providing the contact ID (in ContactID) or email address (in ContactAlt), as well as the list with either the list ID (in ListID) or the list name (in ListAlt).

```
            const addContactToList = await mailjet
            .post("listrecipient", {'version': 'v3'})
            .request({
              "IsUnsubscribed":"false",
              "ContactAlt": req.body.email,
              "ListID":"68539"
            })
```

**Comment by scroll17** [comment]
Hey @wicka-aus 
I reproduced this error and i'm getting the same error message: "ErrorMessage: 'Property "Contact", alternate key value "testemail_01@gmail.com" could not be resolved to an ID'" but this error is correct because i pass an invalid email which not exist in contacts list. 
 
 Below i provide required actions for complete correct what yo want do: 
 1. First you need get a list of all contacts - [GET /contact](https://dev.mailjet.com/email/reference/contacts/contact/#v3_get_contact):
 
 ```javascript
const mailjet = new Mailjet(
  process.env.MJ_APIKEY_PUBLIC,
  process.env.MJ_APIKEY_PRIVATE
)

const request = mailjet
    .get("contact", {'version': 'v3'})
    .request()
    .then((result) => {
        console.dir(result.body, { depth: 10 })
    })
 
 // response
 /**
 * [Object: null prototype] {
 *   Count: 1,
 *   Data: [
 *     [Object: null prototype] {
 *       CreatedAt: '2022-04-13T15:59:02Z',
 *       DeliveredCount: 0,
 *       Email: 'testemail@gmail.com',
 *       ExclusionFromCampaignsUpdatedAt: '',
 *       ID: 40637616,
 *       IsExcludedFromCampaigns: false,
 *       IsOptInPending: false,
 *       IsSpamComplaining: false,
 *       LastActivityAt: '2022-04-13T15:59:02Z',
 *       LastUpdateAt: '2022-04-13T15:59:02Z',
 *       Name: '',
 *       UnsubscribedAt: '',
 *       UnsubscribedBy: ''
 *     }
 *   ],
 *   Total: 1
 * }
 * */
 ```
 **Your email which you want to add to a new list recipient must be here.**
 
 For example:  In this response we see that we have one contact with email 'testemail@gmail.com' - it's my contact in Mailjet
 
 2. The second step is to get all contacts lists  - [GET /contactslist](https://dev.mailjet.com/email/reference/contacts/contact-list#v3_get_contactslist) and you need be sure that in this list exist list which you passed as `ListID` in your code example 
 
 3. The third step is POST request to create a new list recipient - [POST /listrecipient](https://dev.mailjet.com/email/reference/contacts/subscriptions#v3_post_listrecipient): 
 
 Valid code example where i use correct email which exist in list of contacts (first step):
 ```javascript
const mailjet = new Mailjet(
  process.env.MJ_APIKEY_PUBLIC,
  process.env.MJ_APIKEY_PRIVATE
)

const request = mailjet
    .post("listrecipient", {'version': 'v3'})
    .request({
        "IsUnsubscribed": "false",
        "ContactAlt": "testemail@gmail.com  ",
        "ListID": "13228"
    })
    .then((result) => {
        console.dir(result.body, { depth: 10 })
    })
 
 // code above is valid and return response:
 /**
 * [Object: null prototype] {
 *   Count: 1,
 *   Data: [
 *     [Object: null prototype] {
 *       ContactID: 39449366,
 *       ID: 25180366,
 *       IsActive: true,
 *       IsUnsubscribed: false,
 *       ListID: 13228,
 *       ListName: 'MyFirstTest',
 *       SubscribedAt: '',
 *       UnsubscribedAt: ''
 *     }
 *   ],
 *   Total: 1
 * }
 * */
 ```
 Invalid code example where i use incorrect email which not exist in list of contacts (first step):
  ```javascript
const mailjet = new Mailjet(
  process.env.MJ_APIKEY_PUBLIC,
  process.env.MJ_APIKEY_PRIVATE
)

const request = mailjet
    .post("listrecipient", {'version': 'v3'})
    .request({
        "IsUnsubscribed": "false",
        "ContactAlt": "testemail_01@gmail.com  ",
        "ListID": "13228"
    })
    .then((result) => {
        console.dir(result.body, { depth: 10 })
    })
 
 // code above is invalid and return response with error:
/**
 * Error: Unsuccessful: 400 Property "Contact", alternate key value "testemail_01@gmail.com" could not be resolved to an ID
 *     at /home/dzolo/Work/SoftServe/mailjet-apiv3-nodejs/mailjet-client.js:331:23
 *     at Request.callback (/home/dzolo/Work/SoftServe/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/index.js:905:3)
 *     at /home/dzolo/Work/SoftServe/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/index.js:1127:20
 *     at IncomingMessage.<anonymous> (/home/dzolo/Work/SoftServe/mailjet-apiv3-nodejs/node_modules/superagent/lib/node/parsers/json.js:22:7)
 *     at IncomingMessage.emit (node:events:539:35)
 *     at endReadableNT (node:internal/streams/readable:1345:12)
 *     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
 *   ErrorMessage: 'Property "Contact", alternate key value "testemail_01@gmail.com" could not be resolved to an ID',
 *   ErrorIdentifier: undefined,
 *   statusCode: 400
 * }
 * */
 ```

**Comment by scroll17** [comment]
This issue will be closed

**Comment by davidklemme** [comment]
could you please update the documentation? I think its easy to assume you can use the endpoint to create a contact and add it to a list... Tnx @scroll17

**Comment by scroll17** [comment]
Hey @davidklemme
 
Yes, we can do it, and we are already working on the update documentation task. 

And please, open a new issue with this ask.
