### ISSUE TITLE
Use http for API requesting

### ISSUE THREAD

**Issue by dobobaie** [mailjet/mailjet-apiv3-nodejs#202]
Recently I got a SSL error during integration tests because `node-mailjet` request by default on secure connection aka HTTPS
`secure` option with `true` as default value, should be use to define a secure connection or not

**Comment by scroll17** [comment]
Hey @dobobaie 

At the moment I'm running the integration tests on my computer and I don't receive anyone errors. \
I think that an error with `SSL` occurred because that was a problem may be with your host or maybe with the `SSL` certificate on the **Mailjet** server-side. 

Library already had this feature but it was removed in this [PR - use only https](https://github.com/mailjet/mailjet-apiv3-nodejs/pull/139) and I think that using the `HTTPS` instead of `HTTP` it's a good tone because you need always send your `api key` and `api secret` for receiving access to all **Mailjet** features and without `HTTP` you will always send your **secret data** **without secure** that will give access for third-party people and services that is very bad.
