### ISSUE TITLE
Add TS types for Mailjet

### ISSUE THREAD

**Issue by fehergeri13** [mailjet/mailjet-apiv3-nodejs#211]
I'm using the mailjet lib with typescript, and with the earlier versions I used the Email type to assemble a good api request. 

With the latest version (v5.0.0), I lost this export, I had to copy the types from the earlier version, and use that. Is there a change to get that back? I prefer that over reading the https://dev.mailjet.com/email/reference/send-emails#v3_post_send website, also the static type checker is much more effective.

**Comment by scroll17** [comment]
Hey @fehergeri13 

From version `v4.0.0` this library provides its [own TypeScript types](https://github.com/mailjet/mailjet-apiv3-nodejs#typescript), but only on the library level. without types from Mailjet.
For this reason, if you use `@types/node-mailjet` your TS compiler will take types from `node-mailjet` instead of `@types/node-mailjet`.

At the moment we are working to implement and export all TypeScript types for Mailjet and in the near future, we are going to publish it in the news release.

At the moment you can try to use types from `@types/node-mailjet` and `node-mailjet` like this: 
```typescript
import Mailjet from 'node-mailjet';
import { Email } from '@types/node-mailjet';

;(async () => {
  const client = Mailjet.apiConnect('key', 'secret');
  const result = await client
    .get('contact')
    .id(99999)
    .request<{ body: Email.GetResponseData }>();
})();
```

But keep in mind that usages like above throw this TS error: `TS6137: Cannot import type declaration files. Consider importing 'node-mailjet' instead of '@types/node-mailjet'.`

**Comment by scroll17** [comment]
This issue will be closed

**Comment by fehergeri13** [comment]
Why? Is it resolved? I dont think so
