### ISSUE TITLE
Impossible to change the email of a contact in a list?

### ISSUE THREAD

**Issue by Jolg42** [mailjet/mailjet-apiv3-nodejs#64]
Hi there!

I'm scripting this use-case: "A user wants to change its email" and I want to change the email in our DB and providers all at once.

I just did it with Mailchimp and it was fast & easy but every time I want to do something with Mailjet's API either it's not clear or impossible..
Is that doable?

**Comment by kmanchikov** [comment]
Hey there, 

Changing the email address of a contact isn't the best way to tackle this problem. Furthermore we do not provide a way for now to change the email address for a certain contact. I would recommend creating a new entity (contact) with the new email address of that user. 

Let me know if you do have any other questions or concerns, as I would be glad to look into those as well. 

Best, 
Krassimir

**Comment by Jolg42** [comment]
Hi Krassimir,

The main problem here is that I have metadata associated to that user in Mailjet...
So updating the email would be way easier!

Because retrieving the metadata, creating & deleting is just too much 😞

Also the API is not clear, can we add metadata (if they are already defined) with a POST on `/contact`?
Because creating the contact and then doing a PUT on `/contactdata` is again one more step.

**Comment by adamyanliev** [comment]
Hey @Jolg42 ,

I understand your point, however there are several considerations to take into account here. These are the main factors behind this limitation on Mailjet:

 - Maintaining proper deliverability and engagement stats linked to the email address they were sent to. This helps identify possible issues with deliverability to certain domains, for example.
 - The email address is used as an alternative access key to a number of resources, so allowing an email change may cause various issues.
 - Varoius security concerns - e.g. it'd be possible to switch the emails of two different users. 

With further development some of those concerns may be allayed, but for now there are no plans to include an email change functionality for a contact ID.

About adding metadata - this is not possible with POST on `/contact`. However, there are a couple of other options:

1. If the contact needs to be added to a contact list ID, you can use the [`/contactslist/{list_id}/managecontact`](https://dev.mailjet.com/email-api/v3/contactslist-managecontact/) endpoint.  See [here](https://dev.mailjet.com/guides/?javascript#create-contact-and-subscribe-at-once) for a code sample.

2. If you do not want to add the contact to a specific list, you can use `/contact/managemanycontacts` instead. Since the `ContactsLists` object is not mandatory, and you are allowed to add a single contact in `Contacts`, you can use it to add one contact with its metadata into your global list. See [here](https://dev.mailjet.com/guides/?javascript#creating-contacts-with-contact-data) for a code sample. 

Hope that helps :)
Atanas

**Comment by Jolg42** [comment]
Thanks @adamyanliev I can understand these points, however I had a hard time finding your code example, it looks like the link https://dev.mailjet.com/guides/?javascript#create-contact-and-subscribe-at-once doesn't scroll really well to the anchor.

On Firefox:
![screenshot 2018-07-24 at 14 27 50](https://user-images.githubusercontent.com/1328733/43138076-187d4a1c-8f4e-11e8-9aa4-b763972a4628.png)

On Chrome:
![screenshot 2018-07-24 at 14 28 59](https://user-images.githubusercontent.com/1328733/43138090-1fd760cc-8f4e-11e8-84c3-0538dbe8e16f.png)


It works if I paste it a second time in the URL bar ... 😄 

![screenshot 2018-07-24 at 14 31 21](https://user-images.githubusercontent.com/1328733/43138154-45c7abac-8f4e-11e8-8fe3-bc91773c692c.png)

**Comment by adamyanliev** [comment]
Yeah, there are some issues with the top menu, since it loads slower than the rest of the page, so when you're redirected in Chrome initially. you're pointed to the right anchor, but the menu hides the top 100 pixels from the guide. With Firefox it seems there are issues with redirection to lower level headings.

In any case, we'll look into those issues. Thanks for letting us know :)

Atanas
