### ISSUE TITLE
apiKey and apiSecret are undefined

### ISSUE THREAD

**Issue by slim-hmidi** [mailjet/mailjet-apiv3-nodejs#76]
I create an account in mailjet then I followed the instructions mentioned in readme.
I saved the `API_KEY` and `API_SECRET`, I changed them by my credentionals that I found under `API Key Management`

I run these two lines in powershell:
```sh
echo 'export MJ_APIKEY_PUBLIC=MY_API_KEY' >> ~/.zshrc
echo 'export MJ_APIKEY_PRIVATE=MY_API_SECRET' >> ~/.zshrc
```
then I execute this code:
```js
const mailjet = require ('node-mailjet')
    .connect(process.env.MJ_APIKEY_PUBLIC, process.env.MJ_APIKEY_PRIVATE)
console.log(mailjet);
```
I got as a result:
```
MailjetClient {
  config:
   { url: 'api.mailjet.com',
     version: 'v3',
     output: 'json',
     perform_api_call: true,
     secured: true },
  perform_api_call: false,
  version: '3.3.1',
  options: {},
  apiKey: undefined,
  apiSecret: undefined }
```
Do I miss something in my configuration?
**OS: windows 10
mailjet: 3.3.1
node: 8.12.0**

**Comment by HristoKirov** [comment]
Hello,

There are a couple of notes we can make here.

In order to save your API key and secret in the ZSH file you need to be using Z-shell and actually type the commands there. If you are simply using Bash instead you should replace the `zshrc` with `bash_profile`. So the commands would be:

`echo 'export MJ_APIKEY_PUBLIC=XXXX' >> ~/.bash_profile`
`echo 'export MJ_APIKEY_PRIVATE=XXXX' >> ~/.bash_profile`

Also you need to execute the following command `source ~/.zshrc` or `source ~/.bash_profile` afterwords so they can be loaded in the current shell script.

Please note that Powershell does not support bash commands by default, you can instead use a different command-line like Git Bash. Executing the following commands in Git Bash should work just fine and show your keys correctly.

`echo 'export MJ_APIKEY_PUBLIC=XXXX' >> ~/.bash_profile`
`echo 'export MJ_APIKEY_PRIVATE=XXXX' >> ~/.bash_profile`
`source ~/.bash_profile`
`node myapp.js`

I hope this was helpful

**Comment by abambova** [comment]
Hi @slim-hmidi ,

Did the provided solution by @HristoKirov solve your issue? I'm closing this issue as it has been answered and the solution is provided. Please feel free to post a new issue if needed.

Thanks!
