### ISSUE TITLE
changing FromEmail to fake sender mails is not send, and no errors

### ISSUE THREAD

**Issue by webmobiles** [mailjet/mailjet-apiv3-nodejs#78]
I've just  add 'xxx' to FromEmail, to test how i get errors, but i have no errors, but email is not sent.

```
try {
    const resSendEmail: any = await sendContactEmail(viewer, startup, input.message);
    console.log('send email', JSON.stringify(resSendEmail.response));
  } catch (e) {
    throw e;
  }


export async function sendContactEmail(
  issuer: User,
  receiver: Startup,
  message: string
) {
  return sender.request({
    FromEmail: 'xxx' + process.env.MAILJET_API_SENDER,
    Recipients: [{ Email: receiver.email }],
    Vars: {
      receiverFirstName: receiver.name,
      senderFirstName: issuer.firstName,
      senderLastName: issuer.lastName,
      senderEmail: issuer.email,
      message
    }
}
```

I'm getting on the console no errors just the log with the response:

`send  email {"req":{"method":"POST","url":"https://api.mailjet.com/v3/send","data":{"FromEmail":"xxxtest@mydomain.com","FromName":"xxxx","Recipients":[{"Email":"zzzz@gmail.com"}],"Vars":{"receiverFirstName":"test","senderFirstName":"xxx","senderLastName":"xx","senderEmail":"test@gmail.com","message":"seven"}},"headers":{"user-agent":"mailjet-api-v3-nodejs/3.2.1","content-type":"application/json","authorization":"Basic ..."}},"header":{"date":"Tue, 15 Jan 2019 15:07:38 GMT","content-type":"application/json","content-length":"85","connection":"close"},"status":200,"text":"{ \"Sent\" : [{ \"Email\" : \"test@gmail.com\", \"MessageID\" : 1152921504901105820 }] }\n"}

`

why when i remover 'xxx' from the sender: test@mydomain.com, i get the email, but when i add an inexistent email like sender: xxxtest@mydomain.com  , has no errors, catch does not work, but i get response ok, with the details, but email is not sent .... anyone does knox what is happpening?

**Comment by todorDim** [comment]
Hello @webmobiles,

I'll look into this and try to get back to you with some answers. 

Regards,
T.

**Comment by dmitrye** [comment]
`return sender.request({..... `
should be:
`return await sender.request({....`

**Comment by Nikola-Andreev** [comment]
Hi @webmobiles 

When i am trying to represent your scenario i recieve an error wich is properly handled by the catch block. Here is the example:
https://gist.github.com/Nikola-Andreev/d4a385876572003b2b7138dea01f8669
However the error that i am receiving is different from the one you expected, because there is a missing property in the request object.

But when i create a normal request, like in the mailjet code examples but with wrong email i recieve the expected error. Here is the example:
https://gist.github.com/Nikola-Andreev/4a6dc343bac3c01e8f0223e07270546f
And if you change the wrong sender email with an existing one, everything is fine.

Can you please provide more information if the issue still exists, because everything seems normal here.

Regards.

**Comment by webmobiles** [comment]
now is ok
thanks
