### ISSUE TITLE
Scheduling Transactional Emails

### ISSUE THREAD

**Issue by j0b0sapi3n** [mailjet/mailjet-apiv3-nodejs#88]
Hi,

I'm considering using Mailjet but I don't see in the documentation anywhere about scheduling emails to be sent at a later time. For example, schedule a casual follow up welcome email 2 hours after a user signs up instead of right when they sign up.

Is this possible? I thought it'd be a standard feature for most big email providers today.

I saw on this issue in a different repo it seems it's not done yet although I'm not sure if that's for the PHP library: https://github.com/mailjet/mailjet-apiv3-php/issues/128

I'm posting this in the node library since I want to use this in a lambda function.

Thanks,
Jono

**Comment by Nikola-Andreev** [comment]
Hi @j0b0sapi3n 

Unfortunately at the moment MailJet does not provide the ability to send emails at a certain point in the future. But you can easily implement this by yourself with Node.js.
Here are two examples how you can achieve it:

Using setTimeout:
```
sendMailAfterOneMinute();

function sendMailAfterOneMinute() {
    setTimeout(function(){
        sendMail();
    }, 60000); // one minute in milliseconds
}

function sendMail() {
    // TODO add sending mail code here
    console.log("Sending Mail");
}
```
This approach is more suitable for short time executions, for example you want to do something in the next few minutes. The drawback is if you servers stops for some reason all your scheduled jobs will dissapear.That's why for tasks that you want to execute after hours the next approach is better. 

Use a library like node-cron or similar:
https://github.com/node-cron/node-cron

1. Save a record in your DB (for example when the user is  registered)
2. Create a cron job that will be executed on evry 2 hours for example. The job will do the following:
     - Read all the users from DB that you are still not send emails to
     - Send email if the user is registered before more than 1 hour and update the record in the DB to not read this record anymore.

```
const cron = require('node-cron');
cron.schedule('0 */2 * * * ', () => { // execute on every 2 hours
    // TODO
    // Read all the users from DB where send_email = false
    // Send email if the user is registered before more than 1 hour and update the record in the DB to not read this record anymore
});
```
In this case even if your server shut down for some reason, when you start it again you can be sure that the cron job will be executed again.

If have more questions please ask or just close the issue :)

Regards
